obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS) += sunxi-ss.o

obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS_PRNG) += sunxi-ss-rng.o

obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS_CIPHER) += sunxi-ss-cipher.o

obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS_DES) += sunxi-ss-des.o
sunxi-ss-des-y += sunxi-ss-cipher-des.o
obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS_3DES) += sunxi-ss-3des.o
sunxi-ss-3des-y += sunxi-ss-cipher-3des.o

obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS_AES) += sunxi-ss-aes.o
sunxi-ss-aes-y += sunxi-ss-cipher-aes.o

obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS_HASH) += sunxi-ss-hash.o
obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS_MD5) += sunxi-ss-md5.o
sunxi-ss-md5-y += sunxi-ss-hash-md5.o
obj-$(CONFIG_CRYPTO_DEV_SUNXI_SS_SHA1) += sunxi-ss-sha1.o
sunxi-ss-sha1-y += sunxi-ss-hash-sha1.o
